# Generated by Django 2.1.7 on 2019-05-08 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0003_questionnaire_results'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionnaire_results',
            name='education',
            field=models.CharField(choices=[(None, '未選擇'), ('J', '國中'), ('H', '高中'), ('B', '大學'), ('M', '碩士'), ('D', '博士')], default=None, help_text='最高學歷', max_length=1),
        ),
    ]
