# Generated by Django 2.1.7 on 2019-05-28 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0004_auto_20190508_1002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionnaire_results',
            name='annual_income',
            field=models.IntegerField(choices=[(20, '20萬以下'), (40, '21萬至40萬'), (60, '41萬至60萬'), (100, '61萬至100萬'), (101, '100萬以上')]),
        ),
        migrations.AlterField(
            model_name='questionnaire_results',
            name='education',
            field=models.CharField(choices=[('J', '國中'), ('H', '高中'), ('B', '大學'), ('M', '碩士'), ('D', '博士')], max_length=1),
        ),
        migrations.AlterField(
            model_name='questionnaire_results',
            name='gender',
            field=models.CharField(choices=[('Male', '男性'), ('Female', '女性'), ('Others', '其它')], max_length=10),
        ),
    ]
