# Generated by Django 2.1.7 on 2019-05-28 06:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import easy_thumbnails.fields
import userena.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MyProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mugshot', easy_thumbnails.fields.ThumbnailerImageField(blank=True, help_text='A personal image displayed in your profile.', upload_to=userena.models.upload_to_mugshot, verbose_name='mugshot')),
                ('privacy', models.CharField(choices=[('open', 'Open'), ('registered', 'Registered'), ('closed', 'Closed')], default='registered', help_text='Designates who can view your profile.', max_length=15, verbose_name='privacy')),
                ('gender', models.CharField(choices=[('Male', '男性'), ('Female', '女性'), ('Others', '其它')], max_length=10)),
                ('birthday', models.DateField()),
                ('education', models.CharField(choices=[('J', '國中'), ('H', '高中'), ('B', '大學'), ('M', '碩士'), ('D', '博士')], max_length=1)),
                ('annual_income', models.IntegerField(choices=[(20, '20萬以下'), (40, '21萬至40萬'), (60, '41萬至60萬'), (100, '61萬至100萬'), (101, '100萬以上')])),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='my_profile', to=settings.AUTH_USER_MODEL, verbose_name='使用者')),
            ],
            options={
                'permissions': (('view_profile', 'Can view profile'),),
                'abstract': False,
                'default_permissions': ('add', 'change', 'delete'),
            },
        ),
    ]
